baseURL = 'https://blog.overrated.dev/'
languageCode = 'en-us'
title = 'Giovanni Dejan'
theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
    [[menu.main]]
        identifier = "posts"
        url = "/posts/"
        name = "Posts"
        weight = 1
    [[menu.main]]
        identifier = "github"
        url = "https://github.com/iamdejan"
        weight = 2
        pre = "<span data-feather='github'></span>"

[params]
    avatarURL = "https://iamdejan.my.id/processed_images/943767f2c1d84c4c00.webp"
    description = "Just an overrated programmer."
    showPostsOnHomePage = "recent"

[markup]
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 3
        ordered = false
